.TH HEALTH "1" "February 2025" "health version: 1.11.0" "User Commands"
.SH NAME
Health \- Red Hat Enterprise Linux System Administration Quick Check Tool
.SH SYNOPSIS
.B health
[\fI\,OPTION\/\fR]... [\fI\,DIRECTORY\/\fR]...
.SH DESCRIPTION
.TP
Without arguments, general system statistics are displayed and file systems are scrutinized for common errors.
.TP
With arguments, target directories can be specified ( \fB\,health -i\fR /var/log ) or default to present working directory.
.TP
Specific tests can be performed with the options below. \fI\,NOTE:\/\fP some options may require \fB\,sudo\fR.
.SH OPTIONS
.TP
\fB\-e\fR,
parse dmesg for alerts, errors, etc. (may require sudo)
.TP
\fB\-f\fR,
report 10 largest files in specified directory tree
.TP
\fB\-h\fR,
display this help and exit
.TP
\fB\-o\fR,
show users with open files (may require sudo)
.TP
\fB\-p\fR,
display public IP information (if available)
.TP
\fB\-r\fR,
display health on remote host
.TP
\fB\-s\fR,
search for common file permission vulnerabilities
.TP
\fB\-u\fR,
report 10 largest directories by inode usage
.TP
\fB\-v\fR,
display version number and exit
.TP
\fB\-w\fR,
show \fI\,passwd\/\fP info for specified user
.TP
\fB\-z\fR,
display zombie process count, if any
.SH "RED HAT LIFE CYCLE SUPPORT STATUS"
.TS
tab(;);
lb lb lb.
Version;Maintenance Support Ends;Extended Life Cycle Support Ends
_
9;May 31, 2032;May 31, 2035
_
8;May 31, 2029;May 31, 2032
_
7;June 30, 2024;June 30, 2028
_
6;November 30, 2020;June 30, 2024
.TE
.SH AUTHOR
Written by Zac Piatt.
.SH "REPORTING BUGS"
Report any bugs to <zpiatt@protonmail.com>
.SH COPYRIGHT
Copyright \(co 2025 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <https://gnu.org/licenses/gpl.html>.
.br
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
.SH "SEE ALSO"
Full documentation <https://github.com/zpiatt/health>
